---
# Create a ClusterIssuer for step-ca ACME
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: step-ca-acme
spec:
  acme:
    # Step-ca ACME server URL
    server: https://host.docker.internal:8443/acme/acme/directory
    # Email for Let's Encrypt notifications (not used by step-ca but required)
    email: admin@kub.local
    # Secret to store ACME account private key
    privateKeySecretRef:
      name: step-ca-acme-key
    # Skip TLS verification for local step-ca
    skipTLSVerify: true
    # HTTP01 solver configuration
    solvers:
    - http01:
        ingress:
          class: traefik
---
# Create a certificate for testing
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-certificate
  namespace: default
spec:
  secretName: test-certificate-tls
  issuerRef:
    name: step-ca-acme
    kind: ClusterIssuer
  dnsNames:
  - test.kub
  - www.test.kub
