apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
        - name: echo
          image: ealen/echo-server
          ports:
            - containerPort: 80
              name: http
          env:
            - name: PORT
              value: "80"
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: echo
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: echo.kub
spec:
  type: ClusterIP  # Changed from LoadBalancer to ClusterIP for Ingress
  selector:
    app: echo
  ports:
    - port: 80
      targetPort: 80
      name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: step-ca-acme
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect-web-to-websecure@kubernetescrd
spec:
  ingressClassName: traefik  # Using Traefik as the ingress controller
  tls:
  - hosts:
    - echo.kub
    secretName: echo-tls-secret
  rules:
  - host: echo.kub
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: echo
            port:
              name: http
