apiVersion: v1
kind: Service
metadata:
  name: step-ca
  namespace: default
spec:
  ports:
  - port: 8443
    targetPort: 8443
    protocol: TCP
    name: https
  clusterIP: None
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: step-ca
  namespace: default
  labels:
    kubernetes.io/service-name: step-ca
addressType: IPv4
endpoints:
  - addresses:
      - 10.10.0.6
ports:
  - name: https
    protocol: TCP
    port: 8443
