---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-web-to-websecure
  namespace: kube-system
spec:
  redirectScheme:
    scheme: https
    permanent: true
    port: "443"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: redirect-web-to-websecure
  namespace: kube-system
spec:
  entryPoints:
    - web
  routes:
    - match: HostRegexp(`{host:.+}`)
      kind: Rule
      middlewares:
        - name: redirect-web-to-websecure
      services:
        - name: noop@internal
          kind: TraefikService
