---
# ClusterIssuer for step-ca ACME
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: step-ca-acme
spec:
  acme:
    server: https://10.10.0.6:9000/acme/acme-1/directory
    email: admin@kub.local
    privateKeySecretRef:
      name: step-ca-acme-account-key
    skipTLSVerify: true
    solvers:
    - http01:
        ingress:
          class: traefik
