apiVersion: v1
kind: Service
metadata:
  name: step-ca
  namespace: default
spec:
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: https
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: step-ca
  namespace: default
subsets:
- addresses:
  - ip: 10.10.0.6
  ports:
  - port: 9000
    protocol: TCP
    name: https
