apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: step-ca-acme
spec:
  acme:
    server: https://10.10.0.6:9000/acme/acme-1/directory
    email: admin@kub.local
    privateKeySecretRef:
      name: step-ca-acme-account-key
    skipTLSVerify: true
    solvers:
    - http01:
        ingress:
          class: traefik
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-cert
  namespace: default
spec:
  secretName: test-cert-tls
  issuerRef:
    name: step-ca-acme
    kind: ClusterIssuer
  dnsNames:
  - test.kub
  - api.kub
