---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
rules:
- apiGroups: [""]
  resources: ["services","endpoints","pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions","networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list","watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get","create","patch","update"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get","patch","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: kube-system
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: external-dns
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.18.0
        args:
        - --source=service
        - --source=ingress
        - --domain-filter=kub # Only handle .kub domains
        - --provider=coredns # Use CoreDNS provider
        - --coredns-prefix=/etc/coredns # CoreDNS config path
        - --registry=txt # Use TXT records for state management
        - --txt-owner-id=external-dns
        - --interval=1m
        - --log-format=text
        - --log-level=info
        env: []
        # CoreDNS provider doesn't need additional environment variables
        # Original Gandi config (commented out):
        # - name: GANDI_PAT
        #   valueFrom:
        #     secretRef:
        #       name: gandi-api-key
        #       key: api-key
        volumeMounts:
        - name: coredns-config
          mountPath: /etc/coredns
      volumes:
      - name: coredns-config
        hostPath:
          path: /home/lars/k3d-metallb-environment/03-dns/coredns-config
          type: Directory
        # For other providers, use different env vars:
        # Cloudflare: CF_API_EMAIL, CF_API_KEY
        # AWS Route53: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
        # Google Cloud DNS: GOOGLE_APPLICATION_CREDENTIALS
        # Azure DNS: AZURE_CLIENT_ID, AZURE_CLIENT_SECRET, AZURE_TENANT_ID
